[tool.black]
line-length = 119
target-version = ['py36', 'py37', 'py38']
include = '\.pyi?$'

[tool.isort]
known_first_party = "django"
combine_as_imports = true
multi_line_output = 3
line_length = 119
include_trailing_comma = true

[flake8]
max-line-length = 119
